### ISSUE TITLE
When I open the app, it closes immediately

### ISSUE THREAD

**Issue by iliked44444444444** [PlayXboxtion963/Riimote#3]
meizu u10, android 6.0

**Comment by PlayXboxtion963** [comment]
I don't have log or any other information.
Maybe you can try close all other apps, Don't use together with Motionsource or anyother apps which used port 26760

**Comment by PlayXboxtion963** [comment]
[https://github.com/PlayXboxtion963/DSU-AndroidServer/raw/48b96e39adeec82accb86e45f055a1e10c1bb45e/V1.6-withLogDisplay.apk](Debug Version)
Sorry to ignore you problem cause my neglect,Could you try this version? If problem happen it will display log ,pls send to me,thanks

**Comment by PlayXboxtion963** [comment]
Sorry to trouble you .A new version will release tonight, maybe you can try it.
