### ISSUE TITLE
Comparison to DSUController

### ISSUE THREAD

**Issue by git-developer** [PlayXboxtion963/Riimote#7]
Thanks for sharing your project!

When I was looking for smartphone apps providing a DSU server, I found your project and [DSUController](https://github.com/breeze2/dsu-controller-guides). Can you point out advantages, disadvantages or differences between your project and DSUController?

**Comment by PlayXboxtion963** [comment]
Actually my project is a simple software.I don‘t have enough time to maintenance my project. So you can choose what fit you.

**Comment by git-developer** [comment]
Thanks!
