### ISSUE TITLE
Licensing and F-Droid

### ISSUE THREAD

**Issue by NetSysFire** [PlayXboxtion963/Riimote#8]
First of all, thanks for this super useful and versatile application. Now I do not need to borrow my friends switch pro controller anymore and can just use my phone on demand when I have to solve one of those apparatus shrines.

Because it is so useful, have you considered putting it on https://f-droid.org?
If you do not care but would generally allow that, please explicitely say so, I would submit it for you. All credit will still be given to you plus it is now packaged by a trustworthy source and easier to download, especially for F-Droid users like me.

However, in order for this to be able to happen, you must have a license in your project. Every repo on github should have a license ([easy github tutorial](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)) or the default licensing applies, which means, to [quote](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license), with highlighting added:

>However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and **no one may reproduce, distribute, or create derivative works from your work.** If you're creating an open source project, we strongly encourage you to include an open source license.

Which is very likely unintended. You are free to choose whatever license you want, but given I ask in F-Droid context, it would be cool if a compatible license would be chosen (as listed in https://f-droid.org/docs/Inclusion_Policy/), e.g GPL3.0, MIT or Apache 2.0.

**Comment by PlayXboxtion963** [comment]
Thanks for your support ☺️

**Comment by NetSysFire** [comment]
@PlayXboxtion963 You still need to add a LICENSE and give me your explicit permission to submit it to F-Droid.

**Comment by PlayXboxtion963** [comment]
> @PlayXboxtion963 You still need to add a LICENSE and give me your explicit permission to submit it to F-Droid.

Finish.
